### ISSUE TITLE
Question about task selection.

### ISSUE THREAD

**Issue by BaiYu0120** [t-martyniuk/DeblurGAN#1]
Hi, @t-martyniuk. 
Have you ever tried other tasks in Image Restoration, such as Super Resolution and  Noise Reduction. And why did you select the 3 tasks in your thesis? 
Thanks.

**Comment by liujianzhao6328057** [comment]
@BaiYu0120 What's the paper of the code ?

**Comment by t-martyniuk** [comment]
Hi, @BaiYu0120 
Well, while working on the thesis we explored just these 3 specific tasks, though we discussed a lot possibilities of using the same approach for other tasks - SR and denoising are great options, as well, along with "desnowing" and removing rain strikes. We didn't try more than three tasks due to the computational resources limitations  -  one can definitely try more.

**Comment by t-martyniuk** [comment]
@liujianzhao6328057 http://er.ucu.edu.ua/bitstream/handle/1/1332/Martyniuk_%20Multi-task%20learning.pdf?sequence=1&isAllowed=y
